version: '3.4'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: ainode
    volumes:
      - .:/ainode
    ports:
      - "8000:8000"
    env_file: 
      - ./.env.dev
    depends_on: 
      - db
  db:
    image: postgres:12.0-alpine
    container_name: ainode_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=aifunddb
      - POSTGRES_USER=aifunduser
      - POSTGRES_PASSWORD=Nikita123456!

volumes:
  postgres_data: